#!/usr/bin/env node
import { cp, mkdir, readFile, writeFile } from "node:fs/promises"
import { homedir } from "node:os"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const PKG_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")

const DEFAULT_MODELS = {
  ORCHESTRATOR_MODEL: "omniroute/auto/fast",
  FREE_MODEL: "omniroute/auto/fast",
  FAST_MODEL: "omniroute/auto/fast",
  STANDARD_MODEL: "omniroute/auto/coding",
  STRONG_MODEL: "omniroute/auto/smart",
  EXPERT_MODEL: "omniroute/auto/coding:pro",
}

const FLAG_MAP = {
  "--orchestrator": "ORCHESTRATOR_MODEL",
  "--free": "FREE_MODEL",
  "--fast": "FAST_MODEL",
  "--standard": "STANDARD_MODEL",
  "--strong": "STRONG_MODEL",
  "--expert": "EXPERT_MODEL",
}

function parseArgs(argv) {
  const options = { global: false, models: { ...DEFAULT_MODELS } }
  let positionals = 0
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (arg === "init" && positionals === 0) {
      positionals += 1
      continue
    }
    if (arg === "--global") options.global = true
    else if (arg === "--help" || arg === "-h") options.help = true
    else if (FLAG_MAP[arg]) {
      const value = argv[++i]
      if (!value || value.startsWith("--")) throw new Error(`${arg} requires a model id`)
      options.models[FLAG_MAP[arg]] = value
    } else {
      throw new Error(`unknown argument: ${arg} (see --help)`)
    }
  }
  return options
}

function render(template, models) {
  return Object.entries(models).reduce(
    (text, [key, value]) => text.replaceAll(`{{${key}}}`, value),
    template,
  )
}

async function writeAgents(targetDir, models) {
  const agentsDir = join(targetDir, "agents")
  await mkdir(agentsDir, { recursive: true })
  const templates = join(PKG_ROOT, "templates", "agents")
  const files = ["smart-orchestrator.md", "free-worker.md", "smart-fast.md", "smart-standard.md", "smart-strong.md", "expert.md"]
  for (const file of files) {
    const template = await readFile(join(templates, file), "utf8")
    await writeFile(join(agentsDir, file), render(template, models), "utf8")
    console.log(`  agent: ${file}`)
  }
}

async function mergeConfig(targetDir, models) {
  const configPath = join(targetDir, "opencode.json")
  let config = {}
  try {
    config = JSON.parse(await readFile(configPath, "utf8"))
  } catch {
    // no config yet — create one
  }
  config.default_agent = config.default_agent || "smart-orchestrator"
  config.plugin = Array.isArray(config.plugin) ? config.plugin : []
  const entry = ["opencode-omniroute-router", {
    models: {
      "free-worker": models.FREE_MODEL,
      "smart-fast": models.FAST_MODEL,
      "smart-standard": models.STANDARD_MODEL,
      "smart-strong": models.STRONG_MODEL,
      "expert": models.EXPERT_MODEL,
    },
  }]
  const existing = config.plugin.findIndex((p) => Array.isArray(p) && p[0] === "opencode-omniroute-router")
  if (existing >= 0) config.plugin[existing] = entry
  else config.plugin.push(entry)
  await mkdir(dirname(configPath), { recursive: true })
  await writeFile(configPath, JSON.stringify(config, null, 2) + "\n", "utf8")
  console.log(`  config: ${configPath}`)
}

async function main() {
  const options = parseArgs(process.argv.slice(2))

  if (options.help) {
    console.log(`opencode-omniroute-router init

Scaffolds the Smart Orchestrator agents and wires the plugin into an
OpenCode config. Requires an OmniRoute gateway (https://github.com/diegosouzapw/OmniRoute).

Usage:
  opencode-omniroute-router init [options]

Options:
  --global                Install into ~/.config/opencode instead of ./.opencode
  --orchestrator <model>  Orchestrator model     (default: ${DEFAULT_MODELS.ORCHESTRATOR_MODEL})
  --free <model>          Free tier model        (default: ${DEFAULT_MODELS.FREE_MODEL})
  --fast <model>          Fast tier model        (default: ${DEFAULT_MODELS.FAST_MODEL})
  --standard <model>      Standard tier model    (default: ${DEFAULT_MODELS.STANDARD_MODEL})
  --strong <model>        Strong tier model      (default: ${DEFAULT_MODELS.STRONG_MODEL})
  --expert <model>        Expert tier model      (default: ${DEFAULT_MODELS.EXPERT_MODEL})
  -h, --help              Show this help

Models follow the provider/model format used by OpenCode (e.g.
"omniroute/auto/coding" when using the omniroute provider generated by
"omniroute setup-opencode").`)
    return
  }

  const targetDir = options.global ? join(homedir(), ".config", "opencode") : join(process.cwd(), ".opencode")
  console.log(`Installing Smart Orchestrator into ${targetDir}`)

  await writeAgents(targetDir, options.models)
  await mergeConfig(targetDir, options.models)

  console.log(`
Done. Next steps:
  1. Make sure your OpenCode config has an "omniroute" provider pointing at
     your gateway. The official command:
       omniroute setup-opencode   (local)      or
       omniroute setup-opencode --remote http://<host>:20128 --api-key "$OMNIROUTE_API_KEY"
  2. Start OpenCode in this directory and describe a task.
     The smart-orchestrator agent will route it automatically.`)
}

main().catch((error) => {
  console.error(`error: ${error.message}`)
  process.exit(1)
})
